### ISSUE TITLE
English docs?

### ISSUE THREAD

**Issue by vieira-temes** [MTrinkiesJr/MTJR.HardwareMonitor#1]
I just wanted to know if you plan on releasing documentation in English.

Thanks for your work.

**Comment by MTrinkiesJr** [comment]
I already did that, it may come today

**Comment by MTrinkiesJr** [comment]
Okay for english documentation see [Readme english](https://github.com/MTrinkiesJr/MTJR.HardwareMonitor/blob/mutli-gpu-support/readme_en.md)
